-- DBA

-- funcionarios
CREATE TABLE funcionarios (
    MATRICULA INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CARGO VARCHAR(50) NOT NULL,
	DEPARTAMENTO VARCHAR(30) NOT NULL,	 
    salario NUMERIC(11,2) NOT NULL CHECK (salario > 0),
    data_admissao DATE NOT NULL,
    data_demissao DATE,
    CONSTRAINT chk_datas
        CHECK (data_demissao IS NULL OR data_demissao >= data_admissao)
);

-- Solicitações de auxílio
CREATE TABLE SOL_AUX (
	ID_AUX INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	DESCRICAO VARCHAR(100) NOT NULL,
	DATA_REGISTRO DATE NOT NULL DEFAULT CURRENT_DATE, 
	VALOR_AUX NUMERIC(11,2) NOT NULL CHECK (VALOR_AUX > 0),	
	MATRICULA INTEGER NOT NULL,

    CONSTRAINT fk_matricula
        FOREIGN KEY (matricula)
        REFERENCES funcionarios (matricula)
);

-- Pagamentos
CREATE TABLE PAGAMENTOS (
	ID_PAG INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	VALOR_PAG NUMERIC(11,2) NOT NULL CHECK (VALOR_PAG > 0),
	ID_AUX INTEGER,
	MATRICULA INTEGER NOT NULL,
	CONSTRAINT FK_MATRICULA
        FOREIGN KEY (matricula)
        REFERENCES funcionarios (matricula),
	CONSTRAINT FK_SOL_AUX
        FOREIGN KEY (ID_AUX)
        REFERENCES SOL_AUX (ID_AUX)
);

-- log de auditoria
CREATE TABLE log_aud (
    id_log INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    descr_log VARCHAR(100) NOT NULL,
    data_registro DATE NOT NULL DEFAULT CURRENT_DATE
);
